name: Build and Deploy

on:
  # Runs on pushes to the main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.13.1

      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Build project
        run: ./build.bash

      - name: Setup Pages artifact
        run: |
          mkdir -p _site
          cp -r pkg _site/
          cp index.html _site/
          cp elm.js _site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
